In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
print(np.__version__)

1.22.4


In [9]:
#Question 1
orglist = (12.23,13.32,100,36.32)
print(orglist)

(12.23, 13.32, 100, 36.32)


In [10]:
ConvertedArray = np.array(org_list)
print(ConvertedArray)

[ 12.23  13.32 100.    36.32]


In [8]:
#Question 2

In [20]:
NumbersList = (2,3,4,5,6,7,8,9,10)
listHolderArray = np.array(NumbersList)
print(listHolderArray.reshape((3,3)))
matrixd3 = listHolderArray.reshape((3,3))
print(matrixd3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
#Question 3
arrayZeros = np.zeros(10)
print(arrayZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
#The 7th index is the value of 6 (starting from 0)
arrayZeros[6] = 11

In [23]:
print(arrayZeros)
#The printed value is the 7th element of the array

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [30]:
#Question 4
arrayofValuesFrom12to38 = np.arange(12,38)
print(arrayofValuesFrom12to38)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [31]:
#Question 5
arrayofValuesFrom38to12 = arrayofValuesFrom12to38[::-1]
print(arrayofValuesFrom38to12)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [32]:
#Question 6
orgIntValues = [1,2,3,4]
floatValue=np.asfarray(orgIntValues)
print(floatValue)

[1. 2. 3. 4.]


In [33]:
#Question 7
#In the Given Question the Size of 2-D array is assumed to be 5x5 matrix
valuesofOne = np.ones(25)
print(valuesofOne)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


In [34]:
matrixd5 = valuesofOne.reshape(5,5)
print(matrixd5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
matrixd5[1:-1,1:-1] = 0
print(matrixd5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
#Question 8
valuesofOne = np.ones(9)
print(valuesofOne)
matrixd3 = valuesofOne.reshape(3,3)
print(matrixd3)


[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
np.pad(matrixd3,pad_width = 1,mode='constant',constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
#Question 9
print("Checkerboard:")
checkerBoard = np.zeros((8,8))
checkerBoard[1::2,::2] = 1
checkerBoard[::2,1::2] = 1
print(checkerBoard)

Checkerboard:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [41]:
#Question 10
list = (1,2,3,4,5,6,7,8)
array1 = np.array(list)
tuple = ((8,4,6),(1,2,3))
array2 = np.array(tuple)
print(array1)
print(array2)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [42]:
#Question 11
array = [10,20,30]
np.append(array,[[40,50,60],[70,80,90]])


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
 #Question 12
feh_array = [0,12,45.21,34,99.91]
cel_array = []
for i in feh_array:
    cel_array.append((5*(i-32)/9))
    print(i)
print(cel_array)
    #feh_array[i]=(9/5*cel_array[i])-32


0
12
45.21
34
99.91
[-17.77777777777778, -11.11111111111111, 7.33888888888889, 1.1111111111111112, 37.727777777777774]


In [45]:
#Question 13
x = [1,2,3]
x = np.array(x)
print("Size of the array",x.size)
print("Lenght of one array element",x.itemsize)
print("Total Byte consumed by the elements",x.nbytes)

Size of the array 3
Lenght of one array element 4
Total Byte consumed by the elements 12


In [46]:
#Question 14
array1 = [0,10,20,40, 60]
array2 = [10,30,40]
common = []
for i in array1:
    for k in array2:
        if i==k:
            common.append(i)
print(common)

    

[10, 40]


In [47]:
#Question 15
array1 = np.array([10, 10, 20, 20, 30, 30])
print("Unique elements of array1:",np.unique(array1))
array2 = np.array([[1, 1], [2, 3]])
print("Unique elements of array2:",np.unique(array2))



Unique elements of array1: [10 20 30]
Unique elements of array2: [1 2 3]


In [48]:
#Question 16
array1 = np.array([0,10,20,40,60,80])
array2 = np.array([10, 30,40,50,60])
print(np.setdiff1d(array1,array2))

[ 0 20 80]


In [49]:
#Question 17
array2 = np.array([10, 30,40,50,70])
print(np.setxor1d(array1, array2))

[ 0 20 30 50 60 70 80]


In [50]:
#Question 18
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]
print(np.union1d(array1, array2))

[ 0 10 20 30 40 50 60 70 80]


In [51]:
#Question 19
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [52]:
#Question 20
array = [1,2,3,4,5,6]
arrayMax = array[0]
arrayMin = array[0]
for i in array:
    if i>arrayMax:
        arrayMax=i
    if i<arrayMin:
        arrayMin=i
print("The largest value is:",arrayMax)
print("The smallest value is:",arrayMin)
    


The largest value is: 6
The smallest value is: 1


In [53]:
#Question 21
#For printing out indices values, np.nonzero is in use
values = np.array([[0, 10, 20], [20, 30, 40]])
print("Values bigger than 10 =", values[values>10])
print("Their indices are ", np.nonzero(values > 10))

Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [55]:
#Question 22
arrayeros = np.zeros((1,2))
arrayOnes = np.ones((1,2))
print("Array of Zeros:",arrayZeros)
print("Array of Ones:",arrayOnes)

Array of Zeros: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
Array of Ones: [[1. 1.]]


In [56]:
#Question 23
print(np.ravel([[10,20,30],[20,40,50]]))

[10 20 30 20 40 50]


In [57]:
#Question 24
array = [[1,2],[3,4],[5,6]]
print(np.reshape(array,(2,3)))

[[1 2 3]
 [4 5 6]]


In [58]:
#Question 25
arrayInt = [[2,4,6],[6,8,10]]
arrayInt = np.array(arrayInt)
print('Orginal Array',arrayInt)
print(arrayInt.dtype)
arrayInt = arrayInt.astype('float64')
print('Updated Array',arrayInt)
print(arrayInt.dtype)

Orginal Array [[ 2  4  6]
 [ 6  8 10]]
int32
Updated Array [[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


In [59]:
#Question 26
print(np.logspace(2, 5, 20, endpoint=False))

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [60]:
#Question 27
arrayof2Da=[[0,1,3],[5,7,9]]
arrayof2Db=[[0,2,4],[6,8,10]]
arrayof2Da=np.array(arrayof2Da)
arrayof2Db=np.array(arrayof2Db)
np.concatenate((arrayof2Da,arrayof2Db),1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [61]:
#Question 28
array = np.arange(1, 15)
print(array)
print(np.split(array, [2, 6]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [62]:
#Question 29
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [63]:
#Question 30
array = [[0,10,20],[20,30,40]]
array = np.array(array)
print("The total number of non zero element is:{}".format(np.count_nonzero(array)))

The total number of non zero element is:5


In [64]:
#Question 31
array_x = [[10,20,30],[40,50,60]]
array_x = np.array(array_x)
array_y = [[100],[200]]
array_y = np.array(array_y)
print(np.append(array_x,array_y,axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [65]:
#Question 32
array = [-1,-4,0,2,3,4,5,-6]
array = np.array(array)
for (a) in array:
       if array[a]<0:
            array[a]=0
print(array)


[ 0 -4  0  2  3  4  5  0]


In [66]:
#Question 33
#This code removes all the row that contains non numeric variable
#To generate nonnumeric varible np.nan is applied
array = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [1, 0, 1]])
print("The array:", array)
print(array[~np.isnan(array).any(axis=1)])

The array: [[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


In [67]:
#Question 34
a = np.array([97,101,105,111,117])
b = np.array(['a','e','i','o','u'])
for i in range(0,len(a)):
       if(a[i]>100 and a[i]<110):
            print(b[i])


e
i


In [68]:
#Question 35
array = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
elements, counts = np.unique(array, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((elements, counts)))

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [69]:
#Question 36
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[:,[1,2]])

[[2 3]
 [5 6]
 [8 9]]


In [70]:
#Question 37
array = [1,0,2,0,3,0,4,5,6,7,8]
array = np.array(array)
for i in range(0,len(array)):
    if array[i]==0:
        print(i)



1
3
5
